## GGML

# set(GGML_BUILD_TESTS OFF)
# set(GGML_BUILD_EXAMPLES OFF)
# set(GGML_NATIVE OFF)
# set(GGML_STANDALONE OFF)

# set(CMAKE_BUILD_SHARED_LIBS ON)
# set(GGML_BACKEND_DL ON)
# set(GGML_CPU_ALL_VARIANTS ON)

set(GGML_BLAS ON)
set(GGML_BLAS_VENDOR "Generic")
set(GGML_CUDA ON)
set(GGML_AVX_VNNI ON)
set(GGML_CPU ON)
set(GGML_HIP OFF)
set(GGML_OPENCL ON)
set(GGML_VULKAN ON)
set(GGML_VULKAN_SHADERS_GEN_TOOLCHAIN "/usr/bin/glslc")


